import all required libraries

In [1]:
import pandas as pd
import numpy as np

Read files

In [2]:
df =pd.read_csv("C:\\Users\\rites\\OneDrive\\Desktop\\PYTHON AND ML PROJECTS\\bank_data.csv")
df1=pd.read_csv("C:\\Users\\rites\\OneDrive\\Desktop\\PYTHON AND ML PROJECTS\\customer_data.csv")
df2=pd.read_csv("C:\\Users\\rites\\OneDrive\\Desktop\\PYTHON AND ML PROJECTS\\transaction_data.csv")

Analysis bank dataset

check total number of columns and rows

In [3]:
df.shape

(1000, 6)

check null values

In [4]:
df.isnull().sum()

Branch_ID         0
City              0
Region            0
Firm_Revenue     50
Expenses          0
Profit_Margin     0
dtype: int64

Top 5 columns in bank dataset

In [5]:
df.head()

   Branch_ID     City Region  Firm_Revenue  Expenses  Profit_Margin
0       1000  Solapur   East      422443.0    346471          56.31
1       1001   Mumbai  North      211155.0    216256          79.53
2       1002   Nashik   West      985006.0     71777          55.31
3       1003  Solapur  North       55113.0    253655           2.57
4       1004   Nagpur   West      282701.0    148194         -14.10

check  total number of duplicate values

In [6]:
df.duplicated().sum()

0

 check statistical summary of bank dataset

In [7]:
df.describe()

         Branch_ID   Firm_Revenue      Expenses  Profit_Margin
count  1000.000000     950.000000    1000.00000    1000.000000
mean   1499.500000  514074.181053  265325.99100      24.561410
std     288.819436  278665.374536  140572.96154      42.757352
min    1000.000000   51241.000000   20520.00000     -49.500000
25%    1249.750000  260637.500000  145412.75000     -13.470000
50%    1499.500000  518348.500000  265404.00000      24.320000
75%    1749.250000  746103.750000  394530.50000      61.475000
max    1999.000000  999975.000000  499568.00000      99.970000

show the bank dataset's information

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Branch_ID      1000 non-null   int64
 1   City           1000 non-null   object
 2   Region         1000 non-null   object
 3   Firm_Revenue   950 non-null    float64
 4   Expenses       1000 non-null   int64
 5   Profit_Margin  1000 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 47.0+ KB

fill missing value Firm_Revenue

In [9]:
df['Firm_Revenue']=df['Firm_Revenue'].fillna(df['Firm_Revenue'].mean())

In [10]:
df.isnull().sum()

Branch_ID        0
City             0
Region           0
Firm_Revenue     0
Expenses         0
Profit_Margin    0
dtype: int64

Analysis customer's dataset

customer's dataset information

In [11]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_ID    10000 non-null  int64
 1   Age            9500 non-null   float64
 2   Customer_Type  9500 non-null   object
 3   City           9500 non-null   object
 4   Region         10000 non-null  object
 5   Bank_Name      10000 non-null  object
 6   Branch_ID      10000 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 547.0+ KB

TOP 5 columns of customer's dataset

In [12]:
df1.head()

   Customer_ID   Age Customer_Type      City Region  Bank_Name  Branch_ID
0       200000  56.0      Employee      Pune  North  HDFC Bank       1350
1       200001  69.0           NaN  Kolhapur   East  HDFC Bank       1648
2       200002  46.0      Business      Pune   West  HDFC Bank       1798
3       200003  32.0    Individual      Pune   West  HDFC Bank       1900
4       200004   NaN      Business  Kolhapur   East  HDFC Bank       1227

check null values of customer dataset

In [13]:
df1.isnull().sum()

Customer_ID        0
Age              500
Customer_Type    500
City             500
Region             0
Bank_Name          0
Branch_ID          0
dtype: int64

fill missing values

In [14]:
mean_age = round(df1['Age'].mean())

df1['Age'] = df1['Age'].fillna(mean_age)

change data type of age column

In [15]:
df1['Age']=df1['Age'].astype('Int64')

check the age datatype after change float to in

In [16]:
df1['Age'].dtype

Int64Dtype()

In [17]:
df1['Customer_Type']=df1['Customer_Type'].fillna(df1['Customer_Type'].mode().iloc[0])

In [18]:
df1['City']=df1['City'].fillna(df1['City'].mode().iloc[0])

In [19]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_ID    10000 non-null  int64
 1   Age            10000 non-null  Int64
 2   Customer_Type  10000 non-null  object
 3   City           10000 non-null  object
 4   Region         10000 non-null  object
 5   Bank_Name      10000 non-null  object
 6   Branch_ID      10000 non-null  int64
dtypes: Int64(1), int64(2), object(4)
memory usage: 556.8+ KB

check total number of duplicate values of customer dataset

In [20]:
df1.duplicated().sum()

0

check statistical summary of bank dataset

In [21]:
df1.describe()

        Customer_ID        Age     Branch_ID
count   10000.00000    10000.0  10000.000000
mean   204999.50000    48.7667   1497.829300
std      2886.89568  17.465491    288.758237
min    200000.00000       18.0   1000.000000
25%    202499.75000       34.0   1246.000000
50%    204999.50000       49.0   1499.000000
75%    207499.25000       64.0   1747.000000
max    209999.00000       79.0   1999.000000

Analysis transaction dataset

Transaction dataset's information

In [22]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Transaction_ID      10000 non-null  int64
 1   Customer_ID         10000 non-null  int64
 2   Account_Type        10000 non-null  object
 3   Total_Balance       10000 non-null  int64
 4   Transaction_Amount  10000 non-null  float64
 5   Investment_Amount   10000 non-null  int64
 6   Investment_Type     10000 non-null  object
 7   Transaction_Date    10000 non-null  object
dtypes: float64(1), int64(4), object(3)
memory usage: 625.1+ KB

check total number of duplicate values on transaction dataset

In [23]:
duplicate_count = df2.duplicated().sum()
print("Total duplicate rows:", duplicate_count)

Total duplicate rows: 0

check statistical summary of transaction dataset

In [24]:
df2.describe()

,Transaction_ID,Customer_ID,Total_Balance,Transaction_Amount,Investment_Amount
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000
mean,304999.50000,205028.182600,50221.505800,2542.708056,25550.248400
std,2886.89568,2909.008139,28540.392011,1432.677420,14108.052078
min,300000.00000,200000.000000,1003.000000,51.613952,1001.000000
25%,302499.75000,202498.750000,25132.000000,1310.000000,13381.000000
50%,304999.50000,205060.000000,50326.000000,2538.500000,25708.500000
75%,307499.25000,207561.000000,74914.500000,3746.250000,37731.000000
max,309999.00000,209999.000000,99993.000000,7046.296441,49998.000000

Merging all 3 datasets

In [25]:
trans_customer =pd.merge(df2,df1,on='Customer_ID',how='left')
trans_customer

,Transaction_ID,Customer_ID,Account_Type,Total_Balance,Transaction_Amount,Investment_Amount,Investment_Type,Transaction_Date,Age,Customer_Type,City,Region,Bank_Name,Branch_ID
0,300000,209689,Business,69339,4794.0,42580,Fixed Deposit,2024-12-08,68,Individual,Nashik,North,HDFC Bank,1928
1,300001,206124,Business,12825,3500.0,46605,Fixed Deposit,2022-09-09,45,Business,Kolhapur,North,HDFC Bank,1132
2,300002,207501,Current,67753,2401.0,17027,Fixed Deposit,2022-04-28,62,Employee,Solapur,West,HDFC Bank,1690
3,300003,208675,Savings,67061,2952.0,3054,Fixed Deposit,2023-05-22,49,Business,Mumbai,North,HDFC Bank,1032
4,300004,204923,Business,8566,1025.0,44937,Fixed Deposit,2023-04-05,52,Individual,Mumbai,West,HDFC Bank,1653
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,309995,209905,Business,65866,668.0,23300,Recurring Deposit,2025-03-19,75,Employee,Nagpur,South,HDFC Bank,1897
9996,309996,208521,Current,87463,1858.0,49424,Fixed Deposit,2024-05-26,42,Employee,Nashik,East,HDFC Bank,1464
9997,309997,203542,Business,34033,204.0,24744,Mutual Fund,2024-06-19,42,Individual,Pune,East,HDFC Bank,1626
9998,309998,201696,Current,43393,4149.0,9044,Fixed Deposit,2022-09-20,72,Business,Kolhapur,North,HDFC Bank,1613
9999,309999,209682,Savings,43052,3764.0,40989,Recurring Deposit,2025-03-03,35,Employee,Nagpur,West,HDFC Bank,1125

In [26]:
trans_customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Transaction_ID      10000 non-null  int64
 1   Customer_ID         10000 non-null  int64
 2   Account_Type        10000 non-null  object
 3   Total_Balance       10000 non-null  int64
 4   Transaction_Amount  10000 non-null  float64
 5   Investment_Amount   10000 non-null  int64
 6   Investment_Type     10000 non-null  object
 7   Transaction_Date    10000 non-null  object
 8   Age                 10000 non-null  Int64
 9   Customer_Type       10000 non-null  object
 10  City                10000 non-null  object
 11  Region              10000 non-null  object
 12  Bank_Name           10000 non-null  object
 13  Branch_ID           10000 non-null  int64
dtypes: Int64(1), float64(1), int64(5), object(7)
memory usage: 1.1+ MB

In [27]:
final_df=pd.merge(trans_customer,df,on='Branch_ID',how='left')
final_df

,Transaction_ID,Customer_ID,Account_Type,Total_Balance,Transaction_Amount,Investment_Amount,Investment_Type,Transaction_Date,Age,Customer_Type,City_x,Region_x,Bank_Name,Branch_ID,City_y,Region_y,Firm_Revenue,Expenses,Profit_Margin
0,300000,209689,Business,69339,4794.0,42580,Fixed Deposit,2024-12-08,68,Individual,Nashik,North,HDFC Bank,1928,Nashik,North,339233.0,477740,65.87
1,300001,206124,Business,12825,3500.0,46605,Fixed Deposit,2022-09-09,45,Business,Kolhapur,North,HDFC Bank,1132,Kolhapur,West,83336.0,335733,47.84
2,300002,207501,Current,67753,2401.0,17027,Fixed Deposit,2022-04-28,62,Employee,Solapur,West,HDFC Bank,1690,Nashik,North,833490.0,416070,50.07
3,300003,208675,Savings,67061,2952.0,3054,Fixed Deposit,2023-05-22,49,Business,Mumbai,North,HDFC Bank,1032,Nashik,North,722489.0,127639,53.12
4,300004,204923,Business,8566,1025.0,44937,Fixed Deposit,2023-04-05,52,Individual,Mumbai,West,HDFC Bank,1653,Nashik,East,147907.0,80983,17.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,309995,209905,Business,65866,668.0,23300,Recurring Deposit,2025-03-19,75,Employee,Nagpur,South,HDFC Bank,1897,Kolhapur,East,605108.0,447131,-34.94
9996,309996,208521,Current,87463,1858.0,49424,Fixed Deposit,2024-05-26,42,Employee,Nashik,East,HDFC Bank,1464,Nashik,East,104399.0,118487,-21.71
9997,309997,203542,Business,34033,204.0,24744,Mutual Fund,2024-06-19,42,Individual,Pune,East,HDFC Bank,1626,Pune,East,414168.0,372035,61.34
9998,309998,201696,Current,43393,4149.0,9044,Fixed Deposit,2022-09-20,72,Business,Kolhapur,North,HDFC Bank,1613,Kolhapur,North,704298.0,263965,40.67
9999,309999,209682,Savings,43052,3764.0,40989,Recurring Deposit,2025-03-03,35,Employee,Nagpur,West,HDFC Bank,1125,Kolhapur,South,882724.0,350146,72.08

In [28]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Transaction_ID      10000 non-null  int64
 1   Customer_ID         10000 non-null  int64
 2   Account_Type        10000 non-null  object
 3   Total_Balance       10000 non-null  int64
 4   Transaction_Amount  10000 non-null  float64
 5   Investment_Amount   10000 non-null  int64
 6   Investment_Type     10000 non-null  object
 7   Transaction_Date    10000 non-null  object
 8   Age                 10000 non-null  Int64
 9   Customer_Type       10000 non-null  object
 10  City_x              10000 non-null  object
 11  Region_x            10000 non-null  object
 12  Bank_Name           10000 non-null  object
 13  Branch_ID           10000 non-null  int64
 14  City_y              10000 non-null  object
 15  Region_y            10000 non-null  object
 16  Firm_Revenue        10000 non-null  float64
 17  Expenses            10000 non-null  int64
 18  Profit_Margin       10000 non-null  float64
dtypes: Int64(1), float64(3), int64(6), object(9)
memory usage: 1.5+ MB

Load final_df dataset on mysql

 Now Import the 'mysql.connector' library

In [29]:
import mysql.connector

Connect Python with MySQL Server

In [30]:
conn = mysql.connector.connect(
    host="localhost",
    port=3306,
    user="root",
    password="1234",
    database="bank_df"
)

if conn.is_connected():
    print("Connected to bank_df successfully!")

Connected to bank_df successfully!

Create a Cursor and Check Available Tables

In [31]:
cursor = conn.cursor()

cursor.execute("SHOW TABLES")

for table in cursor:
    print(table)

('final_df',)

Upload final_df to MySQL

In [32]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+mysqlconnector://root:1234@localhost:3306/bank_df"
)

final_df.to_sql(
    "final_df",
    con=engine,
    if_exists="replace",
    index=False
)

print("final_df uploaded successfully!")

final_df uploaded successfully!